# Generated by Django 6.0.3 on 2026-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Sanitation', 'Sanitation'), ('Roads & Infrastructure', 'Roads & Infrastructure'), ('Water Supply', 'Water Supply'), ('Drainage', 'Drainage'), ('Street Lights', 'Street Lights'), ('Parks & Public Spaces', 'Parks & Public Spaces')], max_length=100)),
            ],
        ),
    ]
