# Generated by Django 6.0.3 on 2026-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_loginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='user',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginlog',
            name='officer_name',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
    ]
