# Generated by Django 6.0.3 on 2026-03-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('Sanitation', 'Sanitation'), ('Roads & Infrastructure', 'Roads & Infrastructure'), ('Water Supply', 'Water Supply'), ('Drainage', 'Drainage'), ('Street Lights', 'Street Lights'), ('Parks & Public Spaces', 'Parks & Public Spaces')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='complaints/attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.citizen')),
            ],
        ),
    ]
