# Generated by Django 6.0.3 on 2026-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='map_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
