# Generated by Django 6.0.3 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='officer_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
