# Generated by Django 6.0.3 on 2026-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_officer_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='attachment',
            field=models.ImageField(upload_to='complaints/attachments/'),
        ),
    ]
